# Server Port
server.port=8083

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/luxury_fabric_erp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

spring.datasource.username=root
spring.datasource.password=munish2000

# JPA / Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret
luxury.erp.jwtSecret=LuxuryFabricSecretKeyForSecurity2024MustBeLongEnough
luxury.erp.jwtExpirationMs=86400000
jwt.secret=RoyalFabricERPSecretKeyMustBeAtLeast32CharsLong2026
jwt.expiration-ms=86400000